---

- name: create the docker compose directory
  ansible.builtin.file:
    path: "{{ docker_selenium_grid_node_chrome_docker_compose_dir }}"
    state: directory
    mode: 0700

- name: copy docker-compose.yml
  ansible.builtin.template:
    src: templates/docker-compose.yml
    dest: "{{ docker_selenium_grid_node_chrome_docker_compose_dir }}/docker-compose.yml"
    mode: 0700

- name: create the docker build directory
  ansible.builtin.file:
    path: "{{ docker_selenium_grid_node_chrome_docker_build_dir }}"
    state: directory
    mode: 0700

- name: copy the dockerfile
  ansible.builtin.template:
    src: templates/Dockerfile
    dest: "{{ docker_selenium_grid_node_chrome_docker_build_dir }}/Dockerfile"
    mode: 0700

- name: copy the nssdb
  ansible.builtin.copy:
    src: "{{ docker_selenium_grid_node_chrome_nssdb }}"
    dest: "{{ docker_selenium_grid_node_chrome_docker_build_dir }}/nssdb"
    mode: 0700
  when: docker_selenium_grid_node_chrome_nssdb is defined

- name: docker pull selenium/node-chrome-debug
  become: yes
  community.docker.docker_image:
    name: selenium/node-chrome-debug
    tag: "{{ docker_selenium_grid_node_chrome_version }}"
    source: pull
    force_source: yes

- name: docker-compose build --pull
  become: yes
  community.docker.docker_compose:
    project_name: "{{ docker_selenium_grid_node_chrome_project_name }}"
    project_src: "{{ docker_selenium_grid_node_chrome_docker_compose_dir }}"
    build: yes
    nocache: yes
    state: present

- name: docker-compose up
  become: yes
  community.docker.docker_compose:
    project_name: "{{ docker_selenium_grid_node_chrome_project_name }}"
    project_src: "{{ docker_selenium_grid_node_chrome_docker_compose_dir }}"
    state: present

- include_tasks: restart.yml
  when: docker_selenium_grid_node_chrome_restart_always == true
